DROP DATABASE IF EXISTS warehouse;
CREATE DATABASE warehouse; 
USE warehouse;

--  CITIES(CITY CHAR(20),STATE CHAR(20))
CREATE TABLE IF NOT EXISTS CITIES(
	CID INTEGER NOT NULL PRIMARY KEY,
	CITY CHAR(20) NOT NULL,
    STATE CHAR(20) NOT NULL
)AUTO_INCREMENT=1001;

-- WAREHOUSES(WID INTEGER,WNAME CHAR(30),LOCATIONCHAR(20),EXTRA CONTEXT json)
CREATE TABLE IF NOT EXISTS WAREHOUSES(
	WID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    WNAME CHAR(30) NOT NULL,
    LOCATION CHAR(20) NOT NULL
)AUTO_INCREMENT=2001;

-- STORES(SID INTEGER,STORE_NAME CHAR(20), LOCATION_CITYCHAR(20))
CREATE TABLE IF NOT EXISTS STORES(
	SID INTEGER NOT NULL PRIMARY KEY,
    STORE_NAME CHAR(20) NOT NULL,
    LOCATION_CITY CHAR(20) NOT NULL
)AUTO_INCREMENT=3001;

-- CUSTOMER(CNO INTEGER, CNAME CHAR(50),ADDR VARCHAR(50),CU_CITY CHAR(20))
CREATE TABLE IF NOT EXISTS CUSTOMER(
	CNO INTEGER NOT NULL PRIMARY KEY,
    CNAME CHAR(50) NOT NULL,
    ADDR VARCHAR(50) NOT NULL,
    CU_CITY CHAR(20) NOT NULL
)AUTO_INCREMENT=4001;

-- ORDERS(ONO INT,ODATE DATE)
CREATE TABLE IF NOT EXISTS ORDERS(
	ONO INTEGER NOT NULL PRIMARY KEY,
    ODATE DATE NOT NULL
)AUTO_INCREMENT=5001;

-- ITEMS(ITEMNO INTEGER,DESCRIPTION TEXT,WEIGHT DECIMAL(5,2),COST DECIMAL(5,2) )
CREATE TABLE IF NOT EXISTS ITEMS(
	ITEMNO INTEGER NOT NULL PRIMARY KEY,
    DESCRIPTION TEXT NOT NULL,
    WEIGHT DECIMAL(5,2) NOT NULL,
    COST DECIMAL(5,2) NOT NULL
)AUTO_INCREMENT=6001;

-- CITIES-WAREHOUSES 1 TO M
ALTER TABLE warehouses ADD CID INTEGER NOT NULL, ADD FOREIGN KEY(CID) REFERENCES CITIES(CID);

-- WAREHOUSES - STORES 1 TO M
ALTER TABLE STORES ADD WID INTEGER NOT NULL, ADD FOREIGN KEY(WID) REFERENCES WAREHOUSES(WID);

-- CUSTOMER – ORDERS 1 TO M
ALTER TABLE ORDERS ADD CNO INTEGER NOT NULL, ADD FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO);

-- ITEMS – ORDERS M TO M relationship with descriptive attribute ordered_quantity
CREATE TABLE IF NOT EXISTS ordered_quantity(
	ITEMNO INTEGER NOT NULL,
    ONO INTEGER NOT NULL,
    FOREIGN KEY(ITEMNO) REFERENCES items(ITEMNO),
    FOREIGN KEY(ONO) REFERENCES orders(ONO),
    PRIMARY KEY(ITEMNO,ONO)
);

-- STORES-ITEMS M TO M RELATION with descriptive attribute quantity
CREATE TABLE IF NOT EXISTS quantity(
	SID INTEGER NOT NULL,
    ITEMNO INTEGER NOT null,
    FOREIGN KEY(SID) REFERENCES stores(SID),
    FOREIGN KEY(ITEMNO) REFERENCES items(ITEMNO),
    PRIMARY KEY(SID, ITEMNO)
);